# .github/workflows/lint.yml
name: linter

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

permissions:
  contents: write

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Cache Composer Dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Cache NPM Dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-

      - name: Install Project Dependencies
        run: |
          composer install --no-interaction --prefer-dist
          npm install

      - name: Setup Laravel Environment
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Generate Wayfinder Types
        run: php artisan wayfinder:generate --with-form

      - name: Run Laravel Pint
        run: vendor/bin/pint

      - name: Format Frontend Code
        run: npm run format

      - name: Lint Frontend Code
        run: npm run lint

      # Optional: Auto-commit style fixes
      # - name: Commit Style Fixes
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: fix code style
      #     commit_options: '--no-verify'
